# config/opciones.py

PLAZAS = (
    "ACAPULCO",
    "AGUASCALIENTES",
    "CANCUN",
    "CIUDAD DE MEXICO",
    "CIUDAD JUAREZ",
    "COLIMA", 
    "ENSENADA",
    "GUADALAJARA",
    "IRAPUATO",
    "LEON", 
    "MANZANILLO",
    "MAZATLAN", 
    "MERIDA",
    "MONTERREY",
    "MORELIA",
    "PUEBLA",
    "QUERETARO",
    "SAN LUIS POTOSI",
    "TAMPICO",
    "TECOMAN",
    "TIJUANA",
    "VERACRUZ",
    "VILLAHERMOSA",
    "ZACATECAS"
)

EMPRESAS = (
    "CORPORATIVO PUBLICITARIO MAO SA DE CV",
    "DRAUBEN SA DE CV",
    "ESPECIALISTAS PROFESIONALES DE LEON SA DE CV",
    "EPL/VINCI",
    "F2 CONSULTING GROUP SA DE CV",
    "FICORMA SA DE CV",
    "KRONOS AMBIENTAL SAPI DE CV",
    "MARKETING EN PUBLICIDAD DE QUERETARO SA DE CV",
    "MONTAJE SUPERVISION Y CONSTRUCCION SA DE CV",
    "LUMINA PANTALLAS DIGITALES SA DE CV",
    "SERVICIOS DE ANUNCIOS PUBLICITARIOS SA DE CV",
    "SICMART SA DE CV",
    "THE BEST MARKETING SA DE CV",
    "VINCI GERENCIA ORGANIZACIONAL SA DE CV",
)

AREAS = (
    "ADMINISTRATIVA",
    "OPERATIVA"
)

CANALES_RECLUTAMIENTO = (
    "COMPUTRABAJO",
    "HH",
    "INDEED",
    "LONAS",
    "MOVIMIENTO INTERNO",
    "OCC",
    "POSTULACION DIRECTA",
    "REDES PAGADAS",
    "REDES PROPIAS",
    "REFERIDO",
    "REINGRESO",
    "VOLANTEO",
    "SIN ESPECIFICAR"
)

RESPONSABLES_RECLUTAMIENTO = (
    "AGENCIA",
    "DIEGO EDUARDO GOMEZ AZPEITIA",
    "LETICIA SOLIS ZITLALPOPOCATL",
    "MARTA ELENA CHAVEZ SANDOVAL",
    "YULIANA VANESA VAZQUEZ GONZALEZ",
    "SIN ESPECIFICAR"
)

ESTATUS_SOLICITUD = (
    "CANCELADO",
    "CAPTURADA",
    "FINALIZADO",
    "PENDIENTE",
    "PROCESO",
    "RECHAZADA",
)

FASE_PROCESO = (
    "CONTRATADO",
    "EN ENTREVISTA PERSONAL CON CAPITAL HUMANO",
    "EN ENTREVISTA PERSONAL CON GERENCIA DE INSTITUCIONALIZACIÓN / DIRECCIÓN",
    "EN ENTREVISTA PERSONAL CON SOLICITANTE DE LA POSICIÓN",
    "EN ENTREVISTA TELEFONICA",
    "EN INFORME DE LOS CANDIDADATOS SELECCIONADOS",
    "EN PROCESO DE PUBLICACION Y RECLUTAMIENTO",
    "EN PROCESO DE CONTRATACION",
    "EN PRUEBA TÉCNICA",
    "EN PRUEBAS PSICOMETRICAS",
    "EN REVISION Y FILTRO INICIAL DE CANDIDATOS",
    "EN VALIDACION DE REQUISICION DE PERSONAL & DESCRIPCION DE PUESTO",
    "SOLICITUD DE REQUISICION",
    "SIN SOLICITUD DE REQUISICION"
)

TIPO_RECLUTAMIENTO = (
    "MOVIMIENTO LATERAL", 
    "PROMOCION INTERNA",
    "RECLUTAMIENTO EXTERNO",
    "RECLUTAMIENTO INTERNO",
    "REFERIDO INTERNO",
    "SIN ESPECIFICAR"
    )