[client]
showErrorDetails = "none"

[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "100"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "200"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "300"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "400"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "500"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "600"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "700"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "800"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
style = "normal"
weight = "900"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style = "italic"
weight = "100"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style = "italic"
weight = "200"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style = "italic"
weight = "300"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttff"
style = "italic"
weight = "400"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style = "italic"
weight = "500"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style = "italic"
weight = "600"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style = "italic"
weight = "700"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style = "italic"
weight = "800"

[[theme.fontFaces]]
family = "Inter"
url = "app/static/Inter-Italic-VariableFont_opsz,wght.ttf"
style = "italic"
weight = "900"

[theme]
base = "dark"
primaryColor = "#14b8a6"
backgroundColor = "#2a2a2a"
secondaryBackgroundColor = "#121212"
codeBackgroundColor = "#121212"
textColor = "#ffffff"
linkColor = "#14b8a6"
borderColor = "#7c7c7c"
showWidgetBorder = true
baseRadius = "0.3rem"
buttonRadius = "full"
font = "Inter, sans-serif"
baseFontSize = 14
baseFontWeight = 400
headingFont = "Inter, sans-serif"
headingFontSizes = ["2rem", "1.5rem", "1.25rem"]
headingFontWeights = [700, 600, 500]


[theme.sidebar]
backgroundColor = "#121212"
secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#2a2a2a"
borderColor = "#1e3a38"
